services:
  frontend:
    build: .
    container_name: insurance-transfer-frontend
    expose:
      - "3000"
    networks:
       jjline-net
         ipv4_address: 150.50.50.4
networks:
  jjline-net:
    external: true